## Json parsing

In [1]:
#importing required libraries
import pandas as pd
import numpy as np
import json
import matplotlib.pylab as plt
import scipy as sp

In [2]:
# read file
JsonList=[]
for line in open('E:\summit minds\customersdata.json', 'r'):
    JsonList.append(json.loads(line))

In [46]:
#parse file 
JsonList[0]

{'fraudulent': False,
 'customer': {'customerEmail': 'josephhoward@yahoo.com',
  'customerPhone': '400-108-5415',
  'customerDevice': 'yyeiaxpltf82440jnb3v',
  'customerIPAddress': '8.129.104.40',
  'customerBillingAddress': '5493 Jones Islands\nBrownside, CA 51896'},
 'orders': [{'orderId': 'vjbdvd',
   'orderAmount': 18,
   'orderState': 'pending',
   'orderShippingAddress': '5493 Jones Islands\nBrownside, CA 51896'},
  {'orderId': 'yp6x27',
   'orderAmount': 26,
   'orderState': 'fulfilled',
   'orderShippingAddress': '5493 Jones Islands\nBrownside, CA 51896'}],
 'paymentMethods': [{'paymentMethodId': 'wt07xm68b',
   'paymentMethodRegistrationFailure': True,
   'paymentMethodType': 'card',
   'paymentMethodProvider': 'JCB 16 digit',
   'paymentMethodIssuer': 'Citizens First Banks'}],
 'transactions': [{'transactionId': 'a9lcj51r',
   'orderId': 'vjbdvd',
   'paymentMethodId': 'wt07xm68b',
   'transactionAmount': 18,
   'transactionFailed': False},
  {'transactionId': 'y4wcv03i',
   'orderId': 'yp6x27',
   'paymentMethodId': 'wt07xm68b',
   'transactionAmount': 26,
   'transactionFailed': False}]}

In [ ]:
def extract_values(obj, key):
    """Pull all values of specified key from nested JSON."""
    arr = []

    def extract(obj, arr, key):
        """Recursively search for values of key in JSON tree."""
        if isinstance(obj, dict):
            for k, v in obj.items():
                if isinstance(v, (dict, list)):
                    extract(v, arr, key)
                elif k == key:
                    arr.append(v)
        elif isinstance(obj, list):
            for item in obj:
                extract(item, arr, key)
        return arr

    results = extract(obj, arr, key)
    return results

## Customer and order details

In [83]:

Data_cust_Orders=pd.DataFrame(columns=['customerEmail','customerPhone','customerDevice','customerIPAddress','customerBillingAddress','orderId','orderAmount','orderState','orderShippingAddress'])


Rcols=['orderId','orderAmount','orderState','orderShippingAddress']
Scols=['customerEmail','customerPhone','customerDevice','customerIPAddress','customerBillingAddress','fraudulent']
flag='orders'
for num in range(len(JsonList)):
    Orders=pd.DataFrame()
    for i in Rcols:
        val=extract_values(JsonList[num][flag],i)
        Orders[i]=val
    for k in Scols:
        val=extract_values(JsonList[num],k)
        Orders[k]=np.nan
        Orders[k]=Orders[k].fillna(str(val[0]))
    Data_cust_Orders=Data_cust_Orders.append(Orders,ignore_index=True)

Data_cust_Orders.head()

C:\Users\Home\Anaconda3\lib\site-packages\pandas\core\frame.py:6201: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  sort=sort)

,customerBillingAddress,customerDevice,customerEmail,customerIPAddress,customerPhone,fraudulent,orderAmount,orderId,orderShippingAddress,orderState
0,"5493 Jones Islands\nBrownside, CA 51896",yyeiaxpltf82440jnb3v,josephhoward@yahoo.com,8.129.104.40,400-108-5415,False,18,vjbdvd,"5493 Jones Islands\nBrownside, CA 51896",pending
1,"5493 Jones Islands\nBrownside, CA 51896",yyeiaxpltf82440jnb3v,josephhoward@yahoo.com,8.129.104.40,400-108-5415,False,26,yp6x27,"5493 Jones Islands\nBrownside, CA 51896",fulfilled
2,356 Elizabeth Inlet Suite 120\nPort Joshuabury...,r0jpm7xaeqqa3kr6mzum,evansjeffery@yahoo.com,219.173.211.202,1-788-091-7546,True,45,nlghpa,"898 Henry Ports\nNew Keithview, CA 95893-2497",fulfilled
3,356 Elizabeth Inlet Suite 120\nPort Joshuabury...,r0jpm7xaeqqa3kr6mzum,evansjeffery@yahoo.com,219.173.211.202,1-788-091-7546,True,23,uw0eeb,356 Elizabeth Inlet Suite 120\nPort Joshuabury...,fulfilled
4,356 Elizabeth Inlet Suite 120\nPort Joshuabury...,r0jpm7xaeqqa3kr6mzum,evansjeffery@yahoo.com,219.173.211.202,1-788-091-7546,True,43,bn44oh,"5093 Bryan Forks\nJoshuaton, FM 01565-9801",fulfilled

In [85]:
Data_cust_Orders.to_csv('E:\summit minds\Data_cust_Orders.csv')

##  Transactional details

In [102]:
#Data of customer details and orders
#Data_trans_Orders=pd.DataFrame(columns=['customerEmail','customerPhone','customerDevice','customerIPAddress','customerBillingAddress','transactionId','orderId','paymentMethodId','transactionAmount','transactionFailed'])
Data_trans_Orders=pd.DataFrame(columns=['transactionId','orderId','paymentMethodId','transactionAmount','transactionFailed'])

Rcols=['transactionId','orderId','paymentMethodId','transactionAmount','transactionFailed']
Scols=['customerEmail','customerPhone','customerDevice','customerIPAddress','customerBillingAddress','fraudulent']
flag='transactions'
for num in range(len(JsonList)):
    Orders=pd.DataFrame()
    for i in Rcols:
        val=extract_values(JsonList[num][flag],i)
        Orders[i]=val
            
   # for k in Scols:
    #    val=extract_values(JsonList[num],k)
     #   Orders[k]=np.nan
      #  Orders[k]=Orders[k].fillna(str(val[0]))
    Data_trans_Orders=Data_trans_Orders.append(Orders,ignore_index=True)

Data_trans_Orders.head()

  transactionId orderId paymentMethodId transactionAmount transactionFailed
0      a9lcj51r  vjbdvd       wt07xm68b                18             False
1      y4wcv03i  yp6x27       wt07xm68b                26             False
2      5mi94sfw  nlghpa       41ug157xz                45             False
3      br8ba1nu  uw0eeb       41ug157xz                23             False
4      a33145ss  bn44oh       y3xp697jx                43              True

In [93]:
Data_trans_Orders.to_csv('E:\summit minds\Data_trans_Orders.csv')

## Payment method details

In [104]:

#Data_paymnt_Orders=pd.DataFrame(columns=['customerEmail','customerPhone','customerDevice','customerIPAddress','customerBillingAddress','paymentMethodId','paymentMethodRegistrationFailure','paymentMethodType','paymentMethodProvider','paymentMethodIssuer'])
Data_paymnt_Orders=pd.DataFrame(columns=['paymentMethodId','paymentMethodRegistrationFailure','paymentMethodType','paymentMethodProvider','paymentMethodIssuer'])

Rcols=['paymentMethodId','paymentMethodRegistrationFailure','paymentMethodType','paymentMethodProvider','paymentMethodIssuer']
Scols=['customerEmail','customerPhone','customerDevice','customerIPAddress','customerBillingAddress','fraudulent']
flag='paymentMethods'
for num in range(len(JsonList)):
    Orders=pd.DataFrame()
    for i in Rcols:
        val=extract_values(JsonList[num][flag],i)
        Orders[i]=val
            
    #for k in Scols:
     #   val=extract_values(JsonList[num],k)
      #  Orders[k]=np.nan
       # Orders[k]=Orders[k].fillna(str(val[0]))
    Data_paymnt_Orders=Data_paymnt_Orders.append(Orders,ignore_index=True)

Data_paymnt_Orders.head()

,paymentMethodId,paymentMethodRegistrationFailure,paymentMethodType,paymentMethodProvider,paymentMethodIssuer
0,wt07xm68b,True,card,JCB 16 digit,Citizens First Banks
1,y3xp697jx,True,bitcoin,VISA 16 digit,Solace Banks
2,6krszxc05,False,card,VISA 16 digit,Vertex Bancorp
3,5z1szj2he,False,card,Diners Club / Carte Blanche,His Majesty Bank Corp.
4,m52tx8e1s,False,card,Mastercard,Vertex Bancorp

In [96]:
Data_paymnt_Orders.to_csv('E:\summit minds\Data_paymnt_Orders.csv')

## Merging all details into one data set

In [106]:
print(Data_cust_Orders.shape)
print(Data_trans_Orders.shape)
print(Data_paymnt_Orders.shape)

(478, 10)
(623, 5)
(342, 5)

In [112]:
Merged_data=pd.merge(Data_cust_Orders,Data_trans_Orders,on="orderId")
Merged_data=pd.merge(Merged_data,Data_paymnt_Orders,on="paymentMethodId")
print(Merged_data.shape)

(623, 18)

In [111]:
Merged_data.to_csv("E:\summit minds\Merged_data.csv")

In [113]:
Merged_data.head()

,customerBillingAddress,customerDevice,customerEmail,customerIPAddress,customerPhone,fraudulent,orderAmount,orderId,orderShippingAddress,orderState,transactionId,paymentMethodId,transactionAmount,transactionFailed,paymentMethodRegistrationFailure,paymentMethodType,paymentMethodProvider,paymentMethodIssuer
0,"5493 Jones Islands\nBrownside, CA 51896",yyeiaxpltf82440jnb3v,josephhoward@yahoo.com,8.129.104.40,400-108-5415,False,18,vjbdvd,"5493 Jones Islands\nBrownside, CA 51896",pending,a9lcj51r,wt07xm68b,18,False,True,card,JCB 16 digit,Citizens First Banks
1,"5493 Jones Islands\nBrownside, CA 51896",yyeiaxpltf82440jnb3v,josephhoward@yahoo.com,8.129.104.40,400-108-5415,False,26,yp6x27,"5493 Jones Islands\nBrownside, CA 51896",fulfilled,y4wcv03i,wt07xm68b,26,False,True,card,JCB 16 digit,Citizens First Banks
2,356 Elizabeth Inlet Suite 120\nPort Joshuabury...,r0jpm7xaeqqa3kr6mzum,evansjeffery@yahoo.com,219.173.211.202,1-788-091-7546,True,45,nlghpa,"898 Henry Ports\nNew Keithview, CA 95893-2497",fulfilled,5mi94sfw,41ug157xz,45,False,False,bitcoin,American Express,Bastion Banks
3,356 Elizabeth Inlet Suite 120\nPort Joshuabury...,r0jpm7xaeqqa3kr6mzum,evansjeffery@yahoo.com,219.173.211.202,1-788-091-7546,True,23,uw0eeb,356 Elizabeth Inlet Suite 120\nPort Joshuabury...,fulfilled,br8ba1nu,41ug157xz,23,False,False,bitcoin,American Express,Bastion Banks
4,356 Elizabeth Inlet Suite 120\nPort Joshuabury...,r0jpm7xaeqqa3kr6mzum,evansjeffery@yahoo.com,219.173.211.202,1-788-091-7546,True,43,bn44oh,"5093 Bryan Forks\nJoshuaton, FM 01565-9801",fulfilled,a33145ss,y3xp697jx,43,True,True,bitcoin,VISA 16 digit,Solace Banks